const PORTFOLIO_PROJECTS = [
  {
    id: 'bus_sdl2',
    title: 'Projet Bus (C / SDL2)',
    year: 'C',
    shortDesc: 'Simulation/visualisation de lignes de bus : arrêts + tronçons, animation des bus, tri et opérations (fusion/suppression).',
    longDesc: 'Modélisation en C avec structures `Tstation` (ARRET/TRONCON), liste doublement chaînée, tri fusion paramétrable (coût/date + filtres), sauvegarde/chargement d’une ligne, et rendu/animation en SDL2.',
    tech: ['C', 'SDL2', 'Listes doublement chaînées', 'Tri fusion', 'I/O fichier'],
    demoType: 'none',
    demoPath: null,
    videoUrl: null,
    codePath: '../prrojetBOOK/ALOUANI.AMID.TD-04/projetBus/',
  },
  {
    id: 'itl_flex_bison',
    title: 'Projet ITL (Flex / Bison)',
    year: 'Flex/Bison',
    shortDesc: 'Analyse lexicale/syntaxique de commandes de billetterie : validation + extraction + contrainte de cohérence des places.',
    longDesc: 'Série d’exercices Lex/Yacc : reconnaissance d’une commande structurée, somme de places, et vérification que le nombre de places attendu correspond à la liste de numéros fournie (exo 2.3).',
    tech: ['Flex', 'Bison', 'C', 'Tokens', 'Grammaire'],
    demoType: 'none',
    demoPath: null,
    videoUrl: null,
    codePath: '../prrojetBOOK/Projet_ITL/',
  },
  {
    id: 'jpeg_compression',
    title: 'JPEG Compression (C++)',
    year: 'C++',
    shortDesc: 'Implémentation d’une compression type JPEG : DCT/quantif/RLE/Huffman + couleur (YCbCr, sous-échantillonnage).',
    longDesc: 'Pipeline complet (grayscale + couleur), génération d’images de test si besoin, tests sur plusieurs qualités, décompression et métriques (EQM, taux de compression). Build via Makefile.',
    tech: ['C++11', 'DCT/iDCT', 'Quantification', 'RLE', 'Huffman', 'YCbCr'],
    demoType: 'none',
    demoPath: null,
    videoUrl: null,
    codePath: '../prrojetBOOK/JPEG-Projet/',
  },
  {
    id: 'site_amid_f1',
    title: 'Site F1 Teams (XHTML/CSS/JS + XML/DTD)',
    year: 'Web',
    shortDesc: 'Site web multi-pages sur la F1 : interactions DOM, formulaire (validation), style alternatif, XML/DTD pour la collection.',
    longDesc: 'Pages XHTML (collection, calendrier, teams), plan du site repliable, tableau synoptique, formulaire/quiz avec validation JS et champ caché `userAgentInformations`, plus un fichier XML de collection validé par DTD.',
    tech: ['XHTML', 'CSS', 'JavaScript', 'DOM', 'XML', 'DTD'],
    demoType: 'web',
    demoPath: '../prrojetBOOK/SITE_AMID/SITE_AMID/index.xhtml',
    videoUrl: null,
    codePath: '../prrojetBOOK/SITE_AMID/SITE_AMID/',
  },
  {
    id: 'camlbrick',
    title: 'Camlbrick (OCaml + Tk)',
    year: 'OCaml',
    shortDesc: 'Casse-briques : noyau fonctionnel OCaml + interface Tk (Labltk) + documentation HTML.',
    longDesc: 'Modèle de jeu (briques/raquette/balles, états, animation) conçu pour être piloté par une GUI Tk. Présence de doc HTML (ocamldoc) et d’une variante plus compacte avec un fichier de tests.',
    tech: ['OCaml', 'Types algébriques', 'Labltk/Tk', 'Timer', 'Moteur de jeu'],
    demoType: 'none',
    demoPath: null,
    videoUrl: null,
    codePath: '../prrojetBOOK/university-camlbrick/',
  },
  {
    id: 'hack_ap2',
    title: 'Hack AP2 (OCaml) — fuites & hashes',
    year: 'OCaml',
    shortDesc: 'Analyse de fuites de mots de passe : doublons (logins/hashes), hash SHA-256+Base64, corrélation clear↔hash, dictionnaire.',
    longDesc: 'Outils OCaml sur listes + lecture de fichiers “par paires”, hashing via Cryptokit, détection de répétitions et association d’un mot de passe clair à des logins via comparaison de hachages. Rapport PDF fourni.',
    tech: ['OCaml', 'Cryptokit', 'SHA-256', 'Base64', 'Listes'],
    demoType: 'none',
    demoPath: null,
    videoUrl: null,
    codePath: '../prrojetBOOK/ALOUANI_AMID_TD04/ALOUANI_AMID_TD04/',
  },
  {
    id: 'squelette_site',
    title: 'Squelette projet site (template)',
    year: 'Web',
    shortDesc: 'Arborescence attendue pour un projet web (Content/Styles/Javascript/XML/Images) avec pages de redirection.',
    longDesc: 'Dossier “template” contenant uniquement des `index.html` minimalistes dans chaque sous-dossier. Utile comme structure de départ, pas comme site complet exécutable.',
    tech: ['Arborescence web', 'Séparation contenu/styles/scripts'],
    demoType: 'none',
    demoPath: null,
    videoUrl: null,
    codePath: '../prrojetBOOK/SqueletteProjet/SITE_nom1_nom2/',
  },
];
